/* Generated by hphpc — HolyPHP compiler */
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <setjmp.h>
#include <stdarg.h>
#include "hphp_rt.h"



static int hp_main(void) {
    hstr* v0 = hp_null_str();
    int64_t v1 = 0;
    int64_t v2 = 0;
    (v0 = hp_str_lit("World"));
    hp_echo(hp_of_str(hp_str_concat_n(3, (const hval[]){hp_of_str(hp_str_lit("Hello, ")), hp_of_str(v0), hp_of_str(hp_str_lit("!\n"))})));
    (v1 = (int64_t)0);
    {
        (v2 = (int64_t)1);
        for (; hp_le_i((v2), ((int64_t)10)) ;) {
            (v1 += v2);
            (v2 += (int64_t)1);
        }
    }
    hp_echo(hp_of_str(hp_str_concat_n(3, (const hval[]){hp_of_str(hp_str_lit("sum(1..10) = ")), hp_of_int(v1), hp_of_str(hp_str_lit("\n"))})));
    return 0;
}

int main(int argc, char** argv) {
    (void)argc; (void)argv;
    hp_init();
    int _rc = hp_main();
    hp_shutdown();
    return _rc;
}
