/* builtin-docs.js — hand-written explanations for every HolyPHP builtin.
 * Consumed by scripts/gendocs.js (docs/builtins.html) and scripts/genext.js
 * (extension/hphp/data/builtins.json). Keyed by function name.
 * Convention: one or two sentences — what it does, what it returns,
 * notable arguments/edge cases. Written for a developer who knows PHP.
 */
module.exports = {
  /* ============ Strings ============ */
  strlen: "Length of a string in bytes (not characters). For arrays use count().",
  count: "Number of elements in an array, or length of a string. Aliased by sizeof().",
  sizeof: "Alias of count(): elements in an array, bytes in a string.",
  strtoupper: "Converts every ASCII letter in the string to uppercase.",
  strtolower: "Converts every ASCII letter in the string to lowercase.",
  ucfirst: "Uppercases the first character of the string, leaves the rest untouched.",
  lcfirst: "Lowercases the first character of the string, leaves the rest untouched.",
  ucwords: "Uppercases the first letter of every whitespace-separated word.",
  trim: "Strips leading and trailing whitespace (space, tab, newline, CR, NUL).",
  ltrim: "Strips leading whitespace only. Optional second argument: character list to strip.",
  rtrim: "Strips trailing whitespace only. Alias: chop(). Optional second argument: character list.",
  chop: "Alias of rtrim(): strips trailing whitespace.",
  strrev: "Reverses the string byte by byte.",
  str_pad: "Pads the string to the given length with a pad string (default \" \"), repeated on the right.",
  str_replace: "str_replace($search, $replace, $subject) — replaces every occurrence of $search in $subject.",
  substr: "substr($s, $start[, $len]) — extracts up to $len bytes starting at $start. Negative $start counts from the end; omitted $len means \"to the end\".",
  strstr: "Returns the part of $haystack from the first occurrence of $needle to the end, or false if not found.",
  strchr: "Alias of strstr().",
  strpos: "Byte position of the first occurrence of $needle in $haystack, or false when absent. Use !== false to test.",
  str_contains: "true when $needle occurs anywhere in $haystack (PHP 8 style, no position needed).",
  str_starts_with: "true when $haystack begins with $needle.",
  str_ends_with: "true when $haystack ends with $needle.",
  strcmp: "Byte-wise comparison: returns < 0, 0, or > 0 as $a sorts before, equal to, or after $b.",
  strncmp: "Like strcmp() but compares at most the first n bytes (third argument).",
  strcasecmp: "Case-insensitive strcmp().",
  strncasecmp: "Case-insensitive strncmp(): first n bytes, returns -1/0/1 style result.",
  implode: "Joins array elements with a glue string: implode($glue, $arr) or implode($arr).",
  join: "Alias of implode().",
  nl2br: "Inserts \"<br />\" before every newline. Newlines are kept.",
  number_format: "Formats a number with grouped thousands: number_format($n[, $decimals[, $dec_point, $thousands_sep]]). Defaults: 0 decimals, \".\", \",\".",
  nl2br_note: "",
  wordwrap: "Wraps a string to a given width by inserting breaks (default \"\\n\") at word boundaries.",
  substr_count: "Counts how many times $needle occurs in $haystack.",
  str_shuffle: "Randomly shuffles the characters of the string (not cryptographically secure).",
  strip_tags: "Removes HTML and PHP tags from the string.",
  addslashes: "Escapes ' \" \\ and NUL with backslashes — legacy SQL escaping, prefer prepared statements.",
  stripslashes: "Removes backslash escapes added by addslashes().",
  sprintf: "printf-style formatting that returns the string. Supports %d %s %f %x %o %b %e %c, width, precision and \"-\" left-align.",
  printf: "Like sprintf() but prints the result and returns its length.",
  vsprintf: "sprintf() with the arguments taken from an array.",
  ord: "Byte value of the first character of the string (0–255).",
  chr: "One-character string for the given byte value.",
  bin2hex: "Hexadecimal representation of the bytes, two chars per byte: bin2hex(\"AB\") → \"4142\".",
  hex2bin: "Decodes a hexadecimal string back into raw bytes.",
  htmlentities: "Converts & \" ' < > (and more) to their HTML entities so the string is safe to embed as text.",
  htmlspecialchars: "Converts only the five HTML-critical characters & \" ' < > to entities.",
  html_entity_decode: "Inverse of htmlentities(): \"&amp;\" becomes \"&\" again.",
  similar_text: "Number of matching characters between the two strings (a rough similarity measure).",
  levenshtein: "Edit distance (insertions, deletions, substitutions) between the two strings.",
  soundex: "Soundex phonetic key of the string — words that sound alike share the key.",
  metaphone: "Metaphone phonetic key, generally more accurate than soundex() for English.",
  quotemeta: "Backslash-escapes every regex metacharacter (. \\ + * ? [ ] ^ $ ( )).",
  nl2br2: "",

  /* ============ Regex (PCRE-style subset) ============ */
  "preg_match": "preg_match($pattern, $subject[, &$matches]) — tries the pattern once on $subject. Returns 1 and fills $matches (index 0 = full match, 1..n = capture groups) on success, false on no match or bad pattern. Patterns use /.../ delimiters with flags i (case-insensitive), s (dotall), m (multiline).",
  "preg_match_all": "preg_match_all($pattern, $subject[, &$matches]) — finds every non-overlapping match. Returns the number of matches and fills $matches with one array per match (each like preg_match's $matches).",
  "preg_replace": "preg_replace($pattern, $replacement, $subject) — replaces every match. $replacement may reference captures as $1, $2, … Returns the modified string.",
  "preg_split": "preg_split($pattern, $subject) — splits $subject at every match of the pattern and returns the pieces as an array.",
  "preg_grep": "preg_grep($pattern, $array) — returns the elements of $array that match the pattern (keys are re-indexed 0..n).",

  /* ============ Arrays ============ */
  array: "Creates an array from the given values (or \"key\" => value pairs). Usually written as the [...] literal instead.",
  array_keys: "Returns all keys of the array as a new list array.",
  array_values: "Returns all values of the array as a freshly indexed list (0..n-1).",
  array_merge: "Merges two or more arrays; later arrays overwrite string keys of earlier ones, numeric keys are appended.",
  array_slice: "array_slice($arr, $offset[, $length]) — extracts a section of the array. Negative $offset counts from the end.",
  array_reverse: "Returns the array with elements in reverse order.",
  array_sum: "Sum of all numeric values in the array (non-numerics count as 0).",
  array_product: "Product of all numeric values in the array.",
  array_unique: "Removes duplicate values, keeping the first occurrence of each.",
  in_array: "in_array($needle, $haystack) — true when the value occurs in the array.",
  array_key_exists: "true when $key exists in the array (also for string keys and null values).",
  isset: "isset($arr[\"k\"]) — true when the key exists and the value is not null.",
  unset: "unset($arr[\"k\"]) removes the key from the array; unset($var) is not needed for locals.",
  range: "range($start, $end) — list of integers from $start to $end inclusive (also counts down).",
  compact: "Builds an array from the named local variables: compact(\"a\", \"b\") → [\"a\" => $a, \"b\" => $b].",
  array_column: "array_column($rows, $col) — picks one column out of an array of maps, indexed 0..n.",
  array_chunk: "array_chunk($arr, $size) — splits the array into chunks of at most $size elements.",
  array_pad: "array_pad($arr, $size, $value) — grows the array to $size by filling with $value (negative size pads left).",
  array_replace: "array_replace($a, $b, …) — elements of later arrays overwrite those of earlier ones, keys preserved.",
  array_fill_keys: "array_fill_keys([\"a\",\"b\"], $v) — map with those keys, each mapped to $v.",
  array_key_first: "First key of the array (null when empty).",
  array_key_last: "Last key of the array (null when empty).",
  array_flip: "Swaps keys and values: [\"a\" => 1] becomes [1 => \"a\"].",
  array_fill: "array_fill($start, $num, $value) — $num copies of $value starting at index $start.",
  array_combine: "array_combine($keys, $values) — builds a map using one array as keys and the other as values.",
  array_diff: "array_diff($a, $b, …) — values of $a that do not appear in any other array.",
  array_intersect: "array_intersect($a, $b, …) — values of $a that appear in all other arrays.",
  array_push: "Appends one or more values to the end of the array; returns the new count. $arr[] = v is preferred.",
  array_pop: "Removes and returns the last element of the array (null when empty).",
  array_shift: "Removes and returns the first element, re-indexing the rest (null when empty).",
  array_unshift: "Prepends one or more values to the front of the array; returns the new count.",
  array_splice: "array_splice($arr, $offset[, $length[, $replacement]]) — removes a section and optionally replaces it; returns the removed elements.",
  shuffle: "Randomly reorders the array in place (not cryptographically secure).",
  sort: "Sorts the array in place by value, ascending, re-indexing 0..n.",
  rsort: "Sorts the array in place by value, descending, re-indexing.",
  ksort: "Sorts the map in place by key, ascending, keeping key/value association.",
  krsort: "Sorts the map in place by key, descending.",
  asort: "Sorts the map in place by value, ascending, keeping key/value association.",
  arsort: "Sorts the map in place by value, descending, keeping keys.",
  usort: "usort($arr, $cmp) — sorts by value in place using a comparator closure returning -1/0/1.",
  uasort: "usort with key association preserved (for maps).",
  uksort: "Sorts the map in place by key using a comparator closure.",
  array_search: "Returns the key of the first element equal to $needle, or false when not found.",
  array_walk: "array_walk($arr, $fn) — calls $fn($value, $key) for every element; the closure may modify $value via a by-ref parameter.",
  array_walk_recursive: "Like array_walk() but descends into nested arrays.",
  array_map: "array_map($fn, $arr[, $arr2, …]) — applies the closure to every element and returns the results. With several arrays the closure gets one argument per array.",
  array_filter: "array_filter($arr[, $fn]) — keeps elements where $fn returns true; without $fn keeps all truthy elements. Keys are preserved.",
  array_reduce: "array_reduce($arr, $fn[, $initial]) — folds the array left-to-right: $fn($carry, $item).",
  end: "Advances the internal pointer to the last element and returns its value.",
  reset: "Rewinds the internal pointer to the first element and returns its value.",
  max: "Largest of the given numbers or array elements (variadic).",
  min: "Smallest of the given numbers or array elements (variadic).",
  keys: "Alias of array_keys().",
  values: "Alias of array_values().",

  /* ============ Math ============ */
  abs: "Absolute value; keeps the input type (int stays int, float stays float).",
  round: "round($n[, $precision[, $mode]]) — rounds to $precision decimals (default 0). $mode: PHP_ROUND_HALF_UP (default), _HALF_DOWN, _HALF_EVEN, _HALF_ODD.",
  floor: "Largest integer value ≤ $n, returned as float.",
  ceil: "Smallest integer value ≥ $n, returned as float.",
  sqrt: "Square root as float.",
  pow: "pow($base, $exp) — $base raised to $exp.",
  intdiv: "Integer division truncating toward zero: intdiv(7, 2) === 3.",
  fmod: "Floating-point remainder of $x / $y.",
  sin: "Sine of the angle in radians.",
  cos: "Cosine of the angle in radians.",
  tan: "Tangent of the angle in radians.",
  atan: "Arctangent in radians.",
  atan2: "Angle of the point (y, x) — note the argument order.",
  asin: "Arcsine in radians.",
  acos: "Arccosine in radians.",
  log: "Natural logarithm (ln). Optional second argument is the base.",
  log2: "Binary logarithm (base 2).",
  log10: "Common logarithm (base 10).",
  exp: "e raised to the given power.",
  is_nan: "true for the special Not-a-Number float value.",
  is_finite: "true when the float is neither infinite nor NaN.",
  is_infinite: "true for ±infinity.",
  pi: "Returns π as float. The constant M_PI is equivalent.",
  M_PI: "The constant π as a callable fallback — prefer the constant.",
  deg2rad: "Converts degrees to radians.",
  rad2deg: "Converts radians to degrees.",
  hypot: "hypot($a, $b) — length of the hypotenuse sqrt(a² + b²), overflow-safe.",
  lcg_value: "Pseudo-random float in [0, 1) from the combined linear congruential generator (not secure).",
  rand: "rand() → pseudo-random int, or rand($min, $max) within the inclusive range (not secure).",
  mt_rand: "Mersenne-Twister pseudo-random: mt_rand() or mt_rand($min, $max) (faster, still not secure).",
  srand: "Seeds rand() — only useful to get reproducible sequences.",
  mt_srand: "Seeds mt_rand() — only useful to get reproducible sequences.",
  random_int: "Cryptographically secure random integer in [$min, $max]. Prefer this over rand().",
  random_bytes: "random_bytes($n) — $n cryptographically secure random bytes as a raw binary string (max 1024).",

  /* ============ Types & vars ============ */
  is_int: "true when the value is an integer. Aliases: is_integer().",
  is_integer: "Alias of is_int().",
  is_float: "true when the value is a float.",
  is_string: "true when the value is a string.",
  is_bool: "true when the value is true or false.",
  is_array: "true when the value is an array or map.",
  is_null: "true when the value is null.",
  is_numeric: "true when the value is a number or a numeric string like \"42\" or \"3.5\".",
  intval: "Converts to int, truncating floats and parsing the leading integer of strings (0 when not numeric).",
  floatval: "Converts to float. Alias: doubleval().",
  doubleval: "Alias of floatval().",
  strval: "Converts the value to its string representation.",
  boolval: "Converts to bool using PHP truthiness (0, \"\", \"0\", [], null are false).",
  gettype: "Type name as a string: \"int\", \"float\", \"string\", \"bool\", \"array\", \"null\", …",
  var_dump: "Prints type and value of one or more expressions, recursively for arrays — the main debugging tool.",
  print_r: "Human-readable dump of a value (arrays indented). Returns the text instead of printing it.",
  var_export: "Returns a string of PHP code that would recreate the value.",
  serialize: "Serializes the value into a storable string (HolyPHP's own format — do not exchange with PHP's).",
  unserialize: "Restores a value serialized by serialize(). Never unserialize untrusted input.",
  json_encode: "Encodes a value as JSON. Flags: JSON_PRETTY_PRINT (indented), JSON_UNESCAPED_SLASHES (keep /), JSON_NUMERIC_CHECK, JSON_FORCE_OBJECT. Combine with |.",
  json_encode_pretty: "json_encode() with JSON_PRETTY_PRINT pre-applied — convenience wrapper.",
  json_decode: "Decodes a JSON string into arrays/maps/scalars. Optional second argument ($assoc) is accepted for PHP compatibility and ignored.",
  define: "define(\"NAME\", $value) — declares a named constant at runtime.",
  defined: "true when a constant with that name has been defined.",
  constant: "Returns the value of the named constant.",
  get_class: "Class name of an object as a string.",
  method_exists: "true when the object (or class) has that method.",
  property_exists: "true when the object (or class) declares that field.",
  call_user_func: "call_user_func($fn, …$args) — invokes the closure by value; direct calls are preferred.",
  func_get_args: "Arguments the current function actually received (for variadic-style code).",
  func_num_args: "Number of arguments the current function received.",
  type_of: "Returns the type name of the value (same names as gettype).",
  typeof: "Alias of type_of.",

  /* ============ Time & date ============ */
  time: "Current Unix timestamp — seconds since 1970-01-01 UTC.",
  microtime: "Current time as float seconds with microsecond precision (e.g. 1691234567.1234).",
  hrtime: "High-resolution monotonic counter in nanoseconds — use for benchmarking, immune to clock changes.",
  sleep: "Pauses the program for the given number of seconds.",
  usleep: "Pauses the program for the given number of microseconds.",
  sleep_ms: "Pauses for the given number of milliseconds (HolyPHP convenience).",
  date: "date($format[, $timestamp]) — formats the timestamp (default: now) according to $format. Supported: Y y m n d j H G i s a A D l M N W t L U.",
  mktime: "mktime($h, $m, $s, $month, $day, $year) — builds a Unix timestamp from local date/time parts.",
  strtotime: "Parses a date/time string (\"2024-03-15 12:30:00\", \"2024-03-15\", \"12:30:00\") into a Unix timestamp; 0 on failure.",
  checkdate: "checkdate($month, $day, $year) — true when the date is a valid calendar date (knows leap years).",
  strftime: "Locale-style date formatting (subset).",
  getdate: "Timestamp as an associative array: year, mon, mday, hours, minutes, seconds, wday, yday.",
  localtime: "Timestamp as a numeric time-struct array.",
  gmdate: "Like date() but formatted in UTC.",
  exit: "Terminates the program immediately with the given exit code (default 0). Alias: die().",
  die: "Alias of exit().",

  /* ============ System & I/O ============ */
  file_get_contents: "Reads an entire file into a string. Throws when the file cannot be opened.",
  file_put_contents: "file_put_contents($path, $data[, $flags]) — writes the string/binary data to the file. Flag PHP_FILE_APPEND appends instead of truncating.",
  file_exists: "true when a file or directory exists at the path.",
  is_dir: "true when the path is an existing directory.",
  is_file: "true when the path is an existing regular file.",
  is_readable: "true when the file exists and can be read.",
  is_writable: "true when the file exists and can be written.",
  filesize: "Size of the file in bytes.",
  fopen: "fopen($path, $mode) — opens a file handle for streaming (\"r\" read, \"w\" truncate+write, \"a\" append, \"rb\"/\"wb\" binary).",
  fclose: "Closes a file handle opened by fopen(). Always do this for written files.",
  fgets: "Reads one line (up to and including the newline) from a file handle. Returns false at end of file.",
  fread: "fread($handle, $max) — reads up to $max bytes from a file handle.",
  fwrite: "fwrite($handle, $data) — writes the data; returns the number of bytes written.",
  feof: "true when the file handle has reached end of file.",
  fgetc: "Reads a single character from a file handle.",
  mkdir: "mkdir($path[, $recursive]) — creates a directory; with $recursive true it creates parents too.",
  rmdir: "Removes an (empty) directory.",
  unlink: "Deletes a file. Returns true on success.",
  rename: "Renames or moves a file (also across directories).",
  copy: "Copies the file's contents to a new path.",
  touch: "Creates the file if missing, otherwise updates its modification time.",
  dirname: "Directory part of a path: dirname(\"a/b/c.txt\") → \"a/b\".",
  basename: "File name part of a path: basename(\"a/b/c.txt\") → \"c.txt\". Optional second argument strips a suffix.",
  pathinfo: "pathinfo($path) — map with dirname, basename, extension and filename.",
  realpath: "Resolves relative parts and returns the canonical absolute path (false when it does not exist).",
  getcwd: "Current working directory of the process.",
  scandir: "Lists the entries of a directory as an array (including \".\" and \"..\").",
  opendir: "Opens a directory for reading with readdir().",
  readdir: "Returns the next entry name of an opendir() handle, false at the end.",
  exec: "Runs an external command, discards its output, returns the last line (Windows: cmd /c).",
  system: "Runs an external command and prints its output as it arrives.",
  shell_exec: "Runs an external command and returns its complete stdout as a string.",
  passthru: "Runs an external command and forwards its raw binary output to stdout.",
  proc_open: "Starts an external process with separate pipes — advanced process control.",
  readline: "Prints the prompt and reads one line from stdin (for interactive scripts).",
  getenv: "Value of the environment variable (empty string when unset).",
  putenv: "putenv(\"NAME=value\") — sets an environment variable for this process.",
  sys_get_temp_dir: "Path of the system's temporary directory.",
  php_uname: "Operating system description string, e.g. \"Windows NT …\".",
  phpversion: "Version string of the HolyPHP runtime.",
  php_sapi_name: "Interface name — \"cli\" for command line builds.",
  php_sapi: "Alias of php_sapi_name().",
  php_logo_guid: "Returns the logo identifier (kept for PHP-compat novelty; safe to ignore).",
  memory_get_usage: "Bytes currently allocated by the runtime's heap.",
  memory_get_peak_usage: "Largest amount of memory the process has used so far.",
  gc_collect_cycles: "Forces a garbage-collection pass; returns the number of freed objects.",
  sys_getloadavg: "System load average as an array (platform-dependent, mostly informational).",
  bindec: "Parses a binary string (\"1010\") into an integer.",
  octdec: "Parses an octal string (\"777\") into an integer.",
  hexdec: "Parses a hexadecimal string (\"ff\") into an integer.",
  stream_socket_server: "stream_socket_server(\"host:port\") — binds and listens on a TCP socket; returns a server handle (or -1).",
  stream_socket_client: "stream_socket_client(\"host:port\") — connects to a TCP server; returns a socket handle (or -1).",
  stream_socket_accept: "Accepts one incoming connection from a server handle (blocks until a client arrives).",
  stream_socket_accept2: "Like stream_socket_accept() but with a timeout in milliseconds.",
  stream_set_blocking: "Switches a socket handle between blocking and non-blocking mode.",
  stream_recv: "stream_recv($sock[, $max]) — receives up to $max bytes (default 4096) from the socket as a string.",
  stream_send: "stream_send($sock, $data) — sends the string over the socket; returns the bytes sent.",
  stream_eof: "true when the peer closed the connection.",
  stream_peer: "IP:port of the remote end of the socket.",
  stream_close: "Closes a socket handle.",
  http_get: "http_get($url) — performs an HTTP GET (http:// only, no TLS) and returns [\"status\" => 200, \"body\" => …, \"contentType\" => …], or false on failure.",
  http_post: "http_post($url, $body[, $headers]) — HTTP POST with the body string and optional header lines (e.g. \"Content-Type: application/json\"). Same return shape as http_get().",
  http_request: "http_request($url, $method, $body, $headers) — generic HTTP request for custom verbs (PUT, DELETE, …).",
  parse_url: "parse_url($url) — map with scheme, user, host, port, path, query, fragment; missing parts are empty strings, port defaults to 80/443.",
  http_build_query: "Turns a map into an urlencoded query string: [\"a\" => \"x y\"] → \"a=x+y\".",

  /* ============ Hash & encode / crypto ============ */
  md5: "MD5 hash as 32-char hex. Fast but broken for security — checksums only.",
  sha1: "SHA-1 hash as 40-char hex. Also legacy — prefer sha256().",
  sha256: "SHA-256 hash as 64-char hex. The general-purpose hash of this runtime.",
  crc32: "CRC-32 checksum of the data as an integer — detects accidental corruption, not tampering.",
  hash_hmac: "hash_hmac(\"sha256\", $data, $key) — keyed HMAC-SHA256 for signing messages.",
  hash_equals: "Timing-safe string comparison for verifying hashes/signatures — always use it for secrets instead of ===.",
  password_hash: "Creates a salted password hash ($hphp$4096$salt$digest, PBKDF2-SHA256, 4096 rounds). Store this string; never store plain passwords.",
  password_verify: "password_verify($plain, $hash) — recomputes the digest with the hash's salt and compares timing-safely. true when the password matches.",
  base64_encode: "Encodes bytes as Base64 text (with = padding) — for safe transport in JSON, URLs-after-urlencode, etc.",
  base64_decode: "Decodes Base64 back to raw bytes. Invalid characters are skipped.",
  urlencode: "Encodes a string for use in a query string: space becomes +, reserved chars become %XX.",
  urldecode: "Inverse of urlencode().",
  rawurlencode: "Encodes like urlencode() but space becomes %20 (for path segments).",
  rawurldecode: "Inverse of rawurlencode().",
  mysql_escape: "Escapes a string for embedding in a MySQL SQL literal (' \" \\ NUL). Prefer parameterized queries where possible.",

  /* ============ MySQL ============ */
  mysql_connect: "mysql_connect($host[, $port[, $user[, $pass[, $db]]]]) — opens a MySQL/MariaDB connection (native wire protocol, TCP). Returns a connection handle or false.",
  mysql_query: "mysql_query($conn, $sql) — runs a SELECT/SHOW and returns the rows as an array of maps (column name => value), false on error. For INSERT/UPDATE/DELETE use mysql_exec().",
  mysql_exec: "mysql_exec($conn, $sql) — runs a statement and returns the number of affected rows, false on error.",
  mysql_insert_id: "AUTO_INCREMENT value generated by the last INSERT on this connection.",
  mysql_close: "Closes the MySQL connection.",
  mysql_escape: "Escapes a string for safe embedding in SQL text (see the crypto group entry).",

  /* ============ UI (desktop windows) ============ */
  ui_run_main: "Starts the UI event loop — call once after building your windows; blocks until the last window closes.",
  ui_quit: "Ends the UI event loop and closes the application.",
  ui_window: "ui_window($title, $x, $y, $w, $h) — creates a window; returns its handle.",
  ui_show: "ui_show($handle, $visible) — shows or hides a window/control.",
  ui_title: "Sets the window title.",
  ui_size: "ui_size($handle, $w, $h) — resizes a window/control.",
  ui_pos: "ui_pos($handle, $x, $y) — moves a window/control.",
  ui_close: "Destroys a window/control handle.",
  ui_alive: "true while the window/event loop is still running.",
  ui_add: "ui_add($parent, $kind, $text, $x, $y, $w, $h) — adds a control to a window. $kind: 1=window 2=button 3=label 4=input 5=checkbox 6=list 7=combo 8=progress 9=slider 10=group 11=tab 12=panel 13=menu 14=menuitem 15=picture. Returns the control handle.",
  ui_set: "Sets the text of a control (label, button, input value, …).",
  ui_get: "Reads the current text/value of a control (e.g. an input field).",
  ui_enable: "ui_enable($handle, $enabled) — enables/disables a control.",
  ui_move: "Moves a control inside its parent.",
  ui_focus: "Gives the keyboard focus to a control.",
  ui_items: "Number of items in a list/combo control.",
  ui_remove: "ui_remove($handle, $index) — removes an item from a list/combo.",
  ui_clear: "Removes all items from a list/combo (or text from an input).",
  ui_ctrl_show: "Shows/hides a single control.",
  ui_selected: "Index of the selected item in a list/combo (-1 when none).",
  ui_select: "ui_select($handle, $index) — selects an item programmatically.",
  ui_item_text: "Text of the item at the given index.",
  ui_check_get: "true when a checkbox is checked.",
  ui_check_set: "ui_check_set($handle, $checked) — sets a checkbox.",
  ui_progress: "ui_progress($handle, $percent) — sets a progress bar (0–100).",
  ui_slider_get: "Current value of a slider.",
  ui_slider_set: "Sets a slider's value.",
  ui_bg: "ui_bg($handle, $color) — background color (RGB int, e.g. 0xFF0000 for red).",
  ui_fg: "Foreground (text) color as RGB int.",
  ui_font: "ui_font($handle, $size[, $bold[, $italic[, $family]]]) — sets a control's font.",
  ui_menu: "Creates a menu bar / menu for a window.",
  ui_menu_item: "Appends an item to a menu; returns its handle (for ui_on callbacks).",
  ui_menu_sep: "Appends a separator line to a menu.",
  ui_menu_check: "ui_menu_check($handle, $checked) — checkable menu item state.",
  ui_on: "ui_on($handle, $event, $callback) — registers a closure for events: \"click\", \"change\", \"select\", \"close\", … The closure receives event-specific arguments.",
  ui_timer: "ui_timer($ms, $callback) — runs the closure every $ms milliseconds until ui_quit().",
  ui_msg: "ui_msg($win, $title, $text[, $type]) — message box. $type: 0=info 1=warning 2=error 3=question.",
  ui_open_file: "Opens the platform file-open dialog; returns the chosen path or false.",
  ui_save_file: "Opens the platform save-file dialog; returns the chosen path or false.",
  ui_pick_folder: "Folder-picker dialog; returns the path or false.",
  ui_pick_color: "Color-picker dialog; returns the RGB int or false.",
  ui_clip_set: "Copies text to the system clipboard.",
  ui_clip_get: "Reads text from the system clipboard.",

  /* ============ Unsafe / FFI ============ */
  free: "unsafe: frees a raw pointer obtained from FFI. Wrong use corrupts memory — this is why it needs an unsafe block.",
  memcpy: "unsafe: copies $n bytes from one raw address to another.",
  memset: "unsafe: fills $n bytes at an address with a byte value.",
  ffi_load: "unsafe: ffi_load(\"mylib.dll\") — loads a shared library for direct native calls. Returns a library handle or false.",
  ffi_call: "unsafe: ffi_call($lib, \"symbol\") — resolves an exported function in a loaded library; call the result with the documented signature.",
  heap_dump: "Returns a debug dump of the runtime heap (allocation count, sizes).",

  str_repeat: "Repeats the string n times: str_repeat(\"ab\", 3) -> \"ababab\".",
  explode: "explode($separator, $s) - splits the string at every separator into an array. The separator cannot be empty.",
  split: "Alias of explode().",
  str_split: "str_split($s[, $len]) - cuts the string into chunks of $len characters (default 1) and returns them as an array.",
  glob: "glob($pattern) - file paths matching a shell wildcard pattern (\"*.hphp\", \"src/*/*.c\") as an array.",
  stream_ready: "Checks which of the given socket handles are readable (select-style); returns the ready handles as an array.",
  decbin: "Integer to binary string: decbin(10) -> \"1010\".",
  decoct: "Integer to octal string: decoct(8) -> \"10\".",
  dechex: "Integer to hexadecimal string: dechex(255) -> \"ff\".",
  ui_dispatch: "Runs one iteration of the UI event loop (for manual/embedded loops). Prefer ui_run_main().",
  malloc: "unsafe: allocates n bytes of raw memory; returns a pointer for memcpy/memset/ffi. Must be freed with free().",

  /* ============ misc / legacy ============ */
  phpversion: "Version of the HolyPHP runtime (duplicate entry kept for lookup stability).",
  php_sapi: "Alias of php_sapi_name().",
};
