/* genembed.c — generate src/hphpc/runtime_embed.h from the runtime sources.
 *
 * The hphp driver embeds its runtime so an installed hphp binary is fully
 * self-contained. Rebuild the header after changing runtime/*.c:
 *
 *     gcc -O2 -std=c11 scripts/genembed.c -o genembed && ./genembed \
 *         src/hphpc/runtime_embed.h src/hphpc/runtime
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static void emit(FILE *o, const char *sym, const char *path) {
    FILE *f = fopen(path, "rb");
    if (!f) { fprintf(stderr, "cannot open %s\n", path); exit(1); }
    fseek(f, 0, SEEK_END);
    long n = ftell(f);
    fseek(f, 0, SEEK_SET);
    char *b = malloc((size_t)n + 1);
    size_t got = fread(b, 1, (size_t)n, f);
    b[got] = 0;
    fclose(f);
    fprintf(o, "static const char %s[] =\n", sym);
    const char *p = b;
    while (*p) {
        fputc('"', o);
        size_t linelen = 0;
        while (*p && linelen < 60) {
            unsigned char c = (unsigned char)*p;
            if (c == '"')
                fputs("\\\"", o);
            else if (c == '\\')
                fputs("\\\\", o);
            else if (c == '\n') {
                fputs("\\n", o);
                p++;
                linelen++;
                break;
            } else if (c == '\t')
                fputs("\\t", o);
            else if (c < 32)
                fprintf(o, "\\x%02x\"\"", c);
            else
                fputc(c, o);
            p++;
            linelen++;
        }
        fputs("\"\n", o);
    }
    fputs(";\n\n", o);
    free(b);
}

/* The libraries passed on the command line become bundled libraries: their
 * sources are compiled into hphp, so `import "websocket.hphp";` works on an
 * installed compiler with no files on disk. */
static void sanitize(const char *in, char *out, size_t outsz) {
    size_t j = 0;
    for (size_t i = 0; in[i] && j + 1 < outsz; i++) {
        char c = in[i];
        out[j++] = ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
                    (c >= '0' && c <= '9')) ? c : '_';
    }
    out[j] = 0;
}

int main(int argc, char **argv) {
    if (argc < 3) {
        fprintf(stderr, "usage: genembed out.h rtdir [lib.hphp ...]\n");
        return 1;
    }
    FILE *o = fopen(argv[1], "wb");
    if (!o) { perror(argv[1]); return 1; }
    fprintf(o,
            "/* runtime_embed.h — runtime sources embedded in hphp.\n"
            " * Generated by scripts/genembed.c — DO NOT EDIT. */\n"
            "#ifndef HPHP_RUNTIME_EMBED_H\n"
            "#define HPHP_RUNTIME_EMBED_H\n\n");
    char p[512];
    snprintf(p, sizeof p, "%s/hphp_rt.c", argv[2]);
    emit(o, "hp_embed_rt_c", p);
    snprintf(p, sizeof p, "%s/hphp_std.c", argv[2]);
    emit(o, "hp_embed_std_c", p);
    snprintf(p, sizeof p, "%s/hphp_ui.c", argv[2]);
    emit(o, "hp_embed_ui_c", p);
    snprintf(p, sizeof p, "%s/hphp_rt.h", argv[2]);
    emit(o, "hp_embed_rt_h", p);

    /* bundled libraries: name -> source */
    fprintf(o, "/* bundled libraries (lib/*.hphp), by file name */\n"
               "typedef struct { const char *name; const char *src; } HpEmbeddedLib;\n");
    int nlibs = argc > 3 ? argc - 3 : 0;
    for (int i = 0; i < nlibs; i++) {
        char sym[256];
        snprintf(sym, sizeof sym, "hp_embed_lib_%d", i);
        emit(o, sym, argv[3 + i]);
    }
    fprintf(o, "static const HpEmbeddedLib hp_embed_libs[] = {\n");
    for (int i = 0; i < nlibs; i++) {
        const char *base = strrchr(argv[3 + i], '/');
        if (!base) base = strrchr(argv[3 + i], '\\');
        base = base ? base + 1 : argv[3 + i];
        fprintf(o, "    { \"%s\", hp_embed_lib_%d },\n", base, i);
    }
    fprintf(o, "    { NULL, NULL }\n};\n");
    fprintf(o, "static const size_t hp_embed_libs_len = %d;\n", nlibs);
    fprintf(o, "#endif\n");
    fclose(o);
    printf("generated %s\n", argv[1]);
    return 0;
}
